#!/usr/bin/env python3

__description__ = """
MPI-IE workflow for RNA mapping and analysis

usage example:
    RNA-seq -i input-dir -o output-dir mm10
"""


import argparse
import os
import sys
import textwrap
import snakePipes.common_functions as cf
import snakePipes.parserCommon as parserCommon


def parse_args(defaults={"verbose": False, "configFile": None,
                         "clusterConfigFile": None, "maxJobs": 5,
                         "snakemakeOptions": "--use-conda", "tempDir": None,
                         "mode": "alignment,deepTools_qc", "downsample": False,
                         "trim": False, "trimmer": "cutadapt",
                         "trimmerOptions": None, "fastqc": False,
                         "libraryType": 2, "aligner": "STAR",
                         "alignerOptions": None, "salmonIndexOptions": "--type quasi -k 31",
                         "featureCountsOptions": "-C -Q 10 --primary",
                         "filterGTF": None, "sampleSheet": None,
                         "reads": ["_R1", "_R2"],
                         "bwBinSize": 25, "dnaContam": False, "plotFormat": "png",
                         "fromBAM": False, "paired": True,
                         "umidedup": False,
                         "umidedup_opts": "", "bcpattern": "",
                         "umidedup_sep": "_", "umibarcode": False}):
    """
    Parse arguments from the command line.
    """
    mainArgs = parserCommon.mainArguments(defaults, workingDir=False)
    snpArgs = parserCommon.snpArguments(defaults)

    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(__description__),
        parents=[mainArgs, snpArgs],
        add_help=False
    )

    # Workflow options
    optional = parser.add_argument_group('Options')
    optional.add_argument("-m", "--mode",
                          help="workflow running modes (available: 'alignment-free, alignment, allelic-mapping, deepTools_qc')"
                          " (default: '%(default)s')",
                          default=defaults["mode"])

    parserCommon.commonOptions(optional, defaults, bw=True)

    optional.add_argument("--libraryType",
                          help="user provided library type strand specificity. featurCounts style: 0, 1, 2 (Illumina TruSeq); default: '%(default)s')",
                          type=int,
                          default=defaults["libraryType"])

    optional.add_argument("--aligner",
                          help="Program used for mapping: STAR or HISAT2 (default: '%(default)s'). If you change this, please change --alignerOptions to match.",
                          default=defaults["aligner"])

    optional.add_argument("--alignerOptions",
                          help="STAR or hisat2 option string, e.g.: '--twopassMode Basic' (default: '%(default)s')",
                          default=defaults["alignerOptions"])

    optional.add_argument("--salmonIndexOptions",
                          help="Salmon index options, e.g. '--type fmd' (default: '%(default)s')",
                          default=defaults["salmonIndexOptions"])

    optional.add_argument("--featureCountsOptions",
                          help="featureCounts option string. The options '-p -B'"
                               " are always used for paired-end data (default: '%(default)s')",
                          default=defaults["featureCountsOptions"])

    optional.add_argument("--filterGTF",
                          help="filter annotation GTF by grep for use with Salmon, e.g."
                               " use --filterGTF='-v pseudogene'; default: '%(default)s')",
                          default=defaults["filterGTF"])

    optional.add_argument("--sampleSheet",
                          help="Information on samples (required for DE analysis); see "
                               "'docs/content/sampleSheet.example.tsv' for example."
                               " The column names in the tsv files are 'name' and 'condition'. The first entry"
                               " defines which group of samples are control. "
                               " This way, the order of comparison and likewise the sign of values can be changed."
                               " The DE analysis might fail if your sample names begin with a number. So watch out"
                               " for that! (default: '%(default)s')",
                          default=defaults["sampleSheet"])

    optional.add_argument("--dnaContam",
                          action="store_true",
                          help="Returns a plot which presents the proportion of the intergenic reads (default: '%(default)s')",
                          default=defaults["dnaContam"])

    optional.add_argument("--fromBAM",
                         action="store_true",
                         help=argparse.SUPPRESS,default=defaults["fromBAM"])

    optional.add_argument("--single-end",
                          dest="paired",
                          action="store_false",
                          help="input data is single-end, not paired-end. This is only used if --fromBAM is specified.",
                          default=defaults["paired"])

    return parser


def main():
    baseDir, workflowDir, defaults = cf.setDefaults(os.path.basename(__file__))

    # get command line arguments
    parser = parse_args(defaults)
    args = parser.parse_args()
    args, defaults = cf.handleUserArgs(args, defaults, parse_args)

    # we also add these paths to config, although we don't use them in the Snakefile
    args.baseDir = baseDir

    # Common arguments
    cf.checkCommonArguments(args, baseDir, outDir=True)

    ## Begin workflow-specific checks
    # check for Allele-specific mapping mode
    args.allele_mode = cf.checkAlleleParams(args)
    # convert file path to abspath
    if args.allele_mode == "create_and_map":
        args.VCFfile = os.path.abspath(args.VCFfile)
    elif args.allele_mode == "map_only":
        args.SNPfile = os.path.abspath(args.SNPfile)
        args.NMaskedIndex = os.path.abspath(args.NMaskedIndex)
    modeTemp = args.mode.split(",")
    validModes = set(["alignment", "alignment-free", "deepTools_qc", "allelic-mapping"])
    for mode in modeTemp:
        if mode not in validModes:
            sys.exit("{} is not a valid mode!\n".format(mode))
    if "alignment" not in modeTemp and args.umidedup:
        sys.exit("umidedup is only valid for \"alignment\" mode!\n")
    if args.fromBAM and ("alignment-free" in modeTemp or "allelic-mapping" in modeTemp):
        sys.exit("\n--fromBAM can only be used with modes \'alignment\' or \'deepTools_qc\' - use one of these modes or provide fastq files!\n")
    if args.fromBAM:
        args.aligner = "EXTERNAL_BAM"

    ## End workflow-specific checks

    # Handle YAML and log files
    snakemake_cmd = cf.commonYAMLandLogs(baseDir, workflowDir, defaults, args, __file__)
    logfile_name = cf.logAndExport(args, os.path.basename(__file__))

    # Run everything
    cf.runAndCleanup(args, snakemake_cmd, logfile_name)


if __name__ == "__main__":
    main()
