name: snakePipes_CI
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - snakemake=6.2.1
  - fuzzywuzzy
  - mock
  - sphinx=4.2.0
  - sphinx-argparse
  - sphinx_rtd_theme=1.0.0
  - flake8
  - coreutils
  - mamba
