chip_dict:
  sample1:
    control:
    broad: False
  sample2:
    control:
    broad: False
  sample3:
    control:
    broad: False
  sample4:
    control:
    broad: False
  sample5:
    control:
    broad: False
  sample6:
    control:
    broad: False
