#!/usr/bin/env python3

__version__ = "0.8"

__description__ = """
DNA-mapping workflow v{version} - MPI-IE workflow for Hi-C analysis
Vivek Bhardwaj, Fidel Ramirez
September, 2017

usage example:
    HiC -i input-dir -o output-dir mm10
""".format(version=__version__)


import argparse
import os
import signal
import subprocess
import sys
import textwrap
import time
import shutil
import yaml


sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))+"/shared/")
import common_functions as cf


def parse_args(defaults):
    """
    Parse arguments from the command line.
    """

    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(__description__),
        add_help=False
    )

    optional = parser._action_groups.pop()

    ## positional/required
    parser.add_argument("genome",
                        metavar="GENOME",
                        help="Genome acronym of target organism (supported: 'dm3', 'dm6', 'hs37d5', 'mm9', 'mm10', 'SchizoSPombe_ASM294v2')")

    required = parser.add_argument_group('required arguments')
    required.add_argument("-i", "--input-dir",
                        dest="indir",
                        help="input directory containing the paired-end FASTQ files",
                        required=True)

    required.add_argument("-o", "--output-dir",
                        dest="outdir",
                        help="output directory",
                        required=True)

    general = parser.add_argument_group('general arguments')
    general.add_argument("-h", "--help",
                        action="help",
                        help="show this help message and exit")

    general.add_argument("-v", "--verbose",
                        dest="verbose",
                        action="store_true",
                        help="verbose output (default: '%(default)s')",
                        default=defaults["verbose"])

    general.add_argument("-c", "--configfile",
                        dest="configfile",
                        help="configuration file: config.yaml (default: '%(default)s')",
                        default=defaults["configfile"])

    general.add_argument("-j", "--jobs",
                        dest="max_jobs",
                        metavar="INT",
                        help="maximum number of concurrently submitted Slurm jobs / cores if workflow is run locally (default: '%(default)s')",
                        type=int,
                        default=defaults["max_jobs"])

    general.add_argument("--local",
                        dest="local",
                        action="store_true",
                        default=False,
                        help="run workflow locally; default: jobs are submitted to Slurm queue (default: '%(default)s')")

    general.add_argument("--snakemake_options",
                        dest="snakemake_options",
                        metavar="STR",
                        type=str,
                        help="Snakemake options to be passed directly to snakemake, e.g. use "
                        "--snakemake_options='--dryrun --rerun-incomplete --unlock --forceall'. (default: '%(default)s')",
                        default=defaults["snakemake_options"])

    general.add_argument("--tempdir",
                        dest="tempdir",
                        type=str,
                        help="used prefix path for temporary directory created via mktemp. Created temp dir gets exported as "
                        "$TMPDIR and is removed at the end of this wrapper! (default: '%(default)s')",
                        default=defaults["tempdir"])

    ## optional
    parser._action_groups.append(optional)

    parser.add_argument("--downsample",
                        dest="downsample",
                        metavar="INT",
                        help="downsample the given number of reads randomly from of each FASTQ file (default: '%(default)s')",
                        type=int,
                        default=defaults["downsample"])

    parser.add_argument("--trim",
                        dest="trim",
                        action="store_true",
                        help="activate trimming (default: '%(default)s')",
                        default=defaults["trim"])

    parser.add_argument("--trim_prg",
                        dest="trim_prg",
                        choices=['cutadapt', 'trimgalore'],
                        help="trimming program: Cutadapt or TrimGalore (default: '%(default)s')",
                        default=defaults["trim_prg"])

    parser.add_argument("--trim_options",
                        dest="trim_options",
                        metavar="STR",
                        type=str,
                        help="Additional option string for trimming program of choice. (default: '%(default)s')",
                        default=defaults["trim_options"])

    parser.add_argument("--fastqc",
                        dest="fastqc",
                        action="store_true",
                        help="run FastQC read quality control (default: '%(default)s')",
                        default=defaults["fastqc"])

    parser.add_argument("--RF_resolution",
                        dest="RF_resolution",
                        action="store_true",
                        help="Create Hi-C matrices at restriction fragment resolution. Using RF "
                        "resolution would override the --bin_size argument. (default: '%(default)s')",
                        default=defaults["RF_resolution"])

    parser.add_argument("--enzyme",
                        dest="enzyme",
                        choices=['DpnII', 'HindIII'],
                        help="Which enzyme was used to create Hi-C library (default: '%(default)s')",
                        default=defaults["enzyme"])

    parser.add_argument("--bin_size",
                        dest="bin_size",
                        type=int,
                        metavar="INT",
                        help="Create Hi-C matrices at a given bin_size (default: '%(default)s')",
                        default=defaults["bin_size"])

    parser.add_argument("--restrict_region",
                        dest="restrict_region",
                        type=str,
                        metavar="STR",
                        help="Restrict building of HiC Matrix to given region [Chr:Start-End]. "
                        "Only one chromosome can also be specified (default: '%(default)s')",
                        default=defaults["restrict_region"])

    parser.add_argument("--merge_samples",
                        dest="merge_samples",
                        action="store_true",
                        help="Merge all HiC matrices and create a new matrix. (default: '%(default)s')",
                        default=defaults["merge_samples"])

    parser.add_argument("--merge_bins",
                        dest="nbins_toMerge",
                        type=int,
                        help="If > 0 , create a lower resolution HiC matrix for each sample "
                        "by merging the given number of bins. (default: '%(default)s')",
                        default=defaults["nbins_toMerge"])

    parser.add_argument("--findTADs_params",
                        dest="tadparams",
                        type=str,
                        metavar="STR",
                        help="parameters for HiCFindTADs. (default: '%(default)s')",
                        default=defaults["tadparams"])

    args = parser.parse_args()

    args.outdir = os.path.abspath(args.outdir)
    args.cluster_logs_dir = os.path.join(args.outdir, "cluster_logs")

## checks for parameters necessary in wrapper
# 1. Dir path
    if os.path.exists(args.indir):
        args.indir = os.path.abspath(args.indir)
    else:
        print("\nError! Input dir not found! ({})\n".format(args.indir))
        exit(1)
# 2. config file
    if args.configfile and not os.path.exists(args.configfile):
        print("\nError! Provided configfile (-c) not found! ({})\n".format(args.configfile))
        exit(1)

    return args


def main():

    ## basic paths only used in wrapper
    this_script_dir = os.path.dirname(os.path.realpath(__file__))
    main_dir_path = os.path.join(os.path.dirname(os.path.dirname(this_script_dir)))

    ## defaults
    defaults = cf.load_configfile(os.path.join(this_script_dir, "defaults.yaml"),False)
    ## get command line arguments
    args = parse_args(defaults)

    ## we also add these paths to config, although we dont use them in the Snakefile
    args.this_script_dir = this_script_dir
    args.main_dir_path = main_dir_path

    ## merge configuration dicts
    config = defaults   # 1) form defaults.yaml
    if args.configfile:
        user_config = cf.load_configfile(args.configfile,False)
        config = cf.merge_dicts(config, user_config) # 2) form user_config.yaml
    config_wrap = cf.config_diff(vars(args),defaults) # 3) from wrapper parameters
    config = cf.merge_dicts(config, config_wrap)

    ## Output directory + log directory
    subprocess.call("[ -d {cluster_logs_dir} ] || mkdir -p {cluster_logs_dir}".format(cluster_logs_dir=args.cluster_logs_dir), shell=True)

    ## save to configs.yaml in outdir
    cf.write_configfile(os.path.join(args.outdir,'config.yaml'),config)

    snakemake_module_load = "module load snakemake/3.12.0 slurm &&".split()
    snakemake_cmd = """
                    snakemake {snakemake_options} --latency-wait 300 --snakefile {snakefile} --jobs {max_jobs} --directory {outdir} --configfile {configfile}
                    """.format( snakefile = os.path.join(args.this_script_dir, "Snakefile"),
                                max_jobs = args.max_jobs,
                                outdir = args.outdir,
                                snakemake_options = str(args.snakemake_options or ''),
                                configfile = os.path.join(args.outdir,'config.yaml'),
                              ).split()

    if args.verbose:
        snakemake_cmd.append("--printshellcmds")

    if not args.local:
        snakemake_cmd += ["--cluster 'SlurmEasy --threads {threads} --mem-per-cpu 10G --log", args.cluster_logs_dir, "--name {rule}.snakemake'"]

    snakemake_log = "2>&1 | tee -a {}/Hi-C.log".format(args.outdir).split()

    ## create local temp dir and add this path to environment as $TMPDIR variable
    ## on SLURM: $TMPDIR is set, created and removed by SlurmEasy on cluster node
    temp_path = cf.make_temp_dir(args.tempdir, args.outdir, args.verbose)
    snakemake_exports = ("export TMPDIR="+temp_path+" && ").split()

    cmd = " ".join(snakemake_exports + snakemake_module_load + snakemake_cmd + snakemake_log)

    if args.verbose:
        print("\n", cmd, "\n")

    ## Write snakemake_cmd to log file
    with open(os.path.join(args.outdir,"Hi-C.log"),"w") as f:
        f.write(" ".join(sys.argv)+"\n\n")
        f.write(cmd+"\n\n")

    ## Run snakemake
    p = subprocess.Popen(cmd, shell=True)
    if args.verbose:
        print("PID:", p.pid, "\n")
    try:
        p.wait()
    except:
        print("\nWARNING: Snakemake terminated!!!")
        if p.returncode != 0:
            if p.returncode:
                print("Returncode:", p.returncode)

            # kill snakemake and child processes
            subprocess.call(["pkill", "-SIGTERM", "-P", str(p.pid)])
            print("SIGTERM sent to PID:", p.pid)

    ## remove temp dir
    if (temp_path != "" and os.path.exists(temp_path)):
        shutil.rmtree(temp_path, ignore_errors=True)
        if args.verbose:
            print("temp dir removed: "+temp_path+"\n")


if __name__ == "__main__":
    main()
