#!/usr/bin/env python3

__description__ = """
MPI-IE workflow for WGBS analysis

usage example:
    WGBS -i read_input_dir -o output-dir mm10
"""

import argparse
import os
import sys
import textwrap
import snakePipes.common_functions as cf
import snakePipes.parserCommon as parserCommon


def minOne(x):
    """
    Ensure x is an integer >=1
    """
    x = int(x)
    if x < 1:
        raise argparse.ArgumentTypeError("Minimum value of 1 for --maxDist and --minCpGs")
    return x


def bounded01(x):
    """
    Ensure values are bounded [0, 1)
    """
    x = float(x)
    if x < 0 or x >= 1:
        raise argparse.ArgumentTypeError("The values for --minMethDiff, --minAbsDiff, and --FDR must be between 0 and 1")
    return x


def parse_args(defaults={"verbose": False, "configFile": None, "clusterConfigFile":None, "maxJobs": 12, "snakemakeOptions": "--use-conda", "tempDir": None,
                         "downsample": None, "trim": True, "trimmer": "fastp", "trimmerOptions": "-q 5 -l 30 -M 5", "maxDist": 300, "minCpGs": 10, "minMethDiff": 0, "minAbsDiff": 0.1, "FDR": 0.1,
                         "MethylDackelOptions": "--mergeContext --maxVariantFrac 0.25 --minDepth 4", "fastqc": False, 'bwBinSize': 25, 'plotFormat': 'png', "bamExt": '.bam',
                         "blacklist": None, "sampleSheet": None, "mbias": "auto", "fromBAM": False, "skipDOC": False, "skipGCbias": False, "computeDMLs": False}):
    """
    Parse arguments from the command line.
    """
    mainArgs = parserCommon.mainArguments(defaults)

    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(__description__),
        parents=[mainArgs],
        add_help=False
    )

    # Workflow options
    optional = parser.add_argument_group('Options')

    parserCommon.commonOptions(optional, defaults)


    optional.add_argument("--blacklist",
                          dest="blacklist",
                          help="Bed file(s) with positions to mask for methylation calling. Useful for masking SNPs in your strain of interest. (default: '%(default)s')",
                          default=defaults["blacklist"])

    optional.add_argument("--sampleSheet",
                          dest="sampleSheet",
                          help="Perform differential methylation analysis between groups of samples by providing a text file with sample information to use for statistical analysis. (default: '%(default)s')",
                          default=defaults["sampleSheet"])

    # TODO: expand help message
    optional.add_argument("--mbias",
                          dest="mbias",
                          help="Number of nucleotides with methylation bias to ignore during methylation extraction. In the *auto* mode this number is automaticaly calculated by MethylDackel (default: '%(default)s')",
                          default=defaults["mbias"])

    # TODO
    optional.add_argument("--maxDist",
                          type=minOne,
                          help="The maximum distance between CpGs in a DMR (for metilene, default: '%(default)s')",
                          default=defaults["maxDist"])

    # TODO
    optional.add_argument("--minCpGs",
                          type=minOne,
                          help="The minimum number of CpGs in a DMR (for metilene, default: '%(default)s')",
                          default=defaults["minCpGs"])

    # TODO
    optional.add_argument("--minMethDiff",
                          type=float,
                          help="The minimum methylation change in methylation for CpG inclusion in DMR detection (for metilene, default: '%(default)s')",
                          default=defaults["minMethDiff"])

    # TODO
    optional.add_argument("--minAbsDiff",
                          type=float,
                          help="The minimum methylation for returned DMRs (default: '%(default)s')",
                          default=defaults["minAbsDiff"])

    # TODO
    optional.add_argument("--FDR",
                          type=float,
                          help="FDR threshold for returned DMRs (default: '%(default)s')",
                          default=defaults["FDR"])

    optional.add_argument("--MethylDackelOptions",
                          help="Options to pass to MethylDackel extract (default: '%(default)s')",
                          default=defaults["MethylDackelOptions"])

    optional.add_argument("--fromBAM",
                         help="If specified, the input is taking from BAM files containing alignments rather than fastq files. See also --bamExt.",
                         action="store_true")

    optional.add_argument("--bamExt",
                          help="If --fromBAM is specified, this is the expected file extension. Removing it yields sample names. Default: '%(default)s'",
                          default=defaults["bamExt"])

    optional.add_argument("--paired",
                          help="If --fromBAM is specified, this indicates that the input BAM files contain paired-end data. The option is ignored unless --fromBAM is given.",
                          action="store_true")

    optional.add_argument("--computeDMLs",
                          action="store_true",
                          help="Compute differentially methylated loci (DMLs) and regions using DSS. Note that this is currently VERY slow.")

    optional.add_argument("--skipDOC",
                         action="store_true",
                         help="Skip depth of coverage calculation with deepTools.",default=defaults["skipDOC"])

    optional.add_argument("--skipGCbias",
                         action="store_true",
                         help="Skip GC bias calculation with deepTools.",default=defaults["skipGCbias"])

    return parser


def main():
    baseDir, workflowDir, defaults = cf.setDefaults(os.path.basename(__file__))

    # get command line arguments
    parser = parse_args(defaults)
    args = parser.parse_args()
    args, defaults = cf.handleUserArgs(args, defaults, parse_args)

    # we also add these paths to config, although we don't use them in the Snakefile
    args.baseDir = baseDir

    # Common arguments
    cf.checkCommonArguments(args, baseDir, outDir=True)

    # Handle YAML and log files
    snakemake_cmd = cf.commonYAMLandLogs(baseDir, workflowDir, defaults, args, __file__)
    logfile_name = cf.logAndExport(args, os.path.basename(__file__))

    # Run everything
    cf.runAndCleanup(args, snakemake_cmd, logfile_name)


if __name__ == "__main__":
    main()
