{% set version = "3.0.0" %}

package:
  name: snakepipes
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3.11
    - snakemake >=8
    - snakemake-executor-plugin-cluster-generic >=1.0.9
    - pandas
    - graphviz
    - thefuzz
    - pyyaml >=5.1

test:
  commands:
    - DNAmapping --help

about:
  home: 'https://snakepipes.readthedocs.org'
  license: MIT
  summary: NGS processing pipelines from the MPI-IE
