package:
  name: snakepipes
  version: 2.9.0

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
  run:
    - python >=3.7.0
    - snakemake >=6.2.1, <7.19.0
    - tabulate <0.9
    - pandas
    - graphviz
    - thefuzz
    - pyyaml >=5.1
    - coreutils

test:
  commands:
    - DNAmapping --help

about:
  home: 'https://snakepipes.readthedocs.org'
  license: MIT
  summary: NGS processing pipelines from the MPI-IE
  license_file: LICENSE
