{% set version = "3.0.1" %}

package:
  name: snakepipes
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: pip install .

requirements:
  host:
    - python >=3
    - pip
    - seaborn
  run:
    - python >=3.11
    - snakemake >=8
    - snakemake-executor-plugin-cluster-generic >=1.0.9
    - pandas
    - thefuzz
    - pyyaml >=5.1

test:
  commands:
    - DNAmapping --help

about:
  home: 'https://snakepipes.readthedocs.org'
  license: MIT
  summary: NGS processing pipelines from the MPI-IE
