#!/usr/bin/env python3

__version__ = "0.1.1"

__description__ = """
DNA-mapping workflow v{version} - MPI-IE workflow for DNA mapping
Fabian Kilpert, Andreas Richter
June 17, 2016

usage example:
    DNA-mapping -g mm10 -i input-dir -o output-dir
""".format(version=__version__)


import argparse
import os
import signal
import subprocess
import sys
import textwrap
import time


def parse_args():
    """
    Parse arguments from the command line.
    """

    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        formatter_class=argparse.RawDescriptionHelpFormatter, description=textwrap.dedent(__description__)
    )

    ## optional
    parser.add_argument("-g", "--genome", dest="genome", required=True, help="genome acronym of target organism (supported: 'dm6', 'hs37d5', 'mm9', 'mm10')")
    parser.add_argument("-c", "--configfile", dest="configfile", help="configuration file (config.yaml)", default=None)
    parser.add_argument("-i", "--input-dir", dest="indir", help="input directory containing the FASTQ files (default: '.')", default=None)
    parser.add_argument("-o", "--output-dir", dest="outdir", help="output directory (default: '.')", default=None)
    parser.add_argument("-j", "--jobs", dest="max_jobs", metavar="INT", help="maximum number of concurrently submitted Slurm jobs / cores if workflow is run locally (default: '%(default)s')", type=int, default=8)
    parser.add_argument("--local", dest="local", action="store_true", default=False, help="run workflow locally (default: jobs are submitted to Slurm queue)")
    parser.add_argument("-r", "--rerun-incomplete", dest="rerun_incomplete", action="store_true", default=False, help="rerun all jobs with incomplete output files")
    parser.add_argument("-F", "--forceall", dest="forceall", action="store_true", default=False, help="force full rerun")
    parser.add_argument("--downsample", dest="downsample", metavar="INT", help="downsample the given number of reads from the head of each FASTQ file", type=int, default=None)
    parser.add_argument("--trim", dest="trim", action="store_true", default=False, help="trim reads with TrimGalore")
    parser.add_argument("--fastqc", dest="fastqc", action="store_true", default=False, help="run FastQC read quality control")
    parser.add_argument("--bw-binsize", dest="bw_binsize", metavar="INT", help="bin size of output files in bigWig format (default: '%(default)s')", type=int, default=10)
    parser.add_argument("-v", "--verbose", dest="verbose", action="store_true", default=False, help="verbose output")

    ## positional
    ## None

    args = parser.parse_args()

    ## Variable sanity checking
    ## None

    ## correction to variables
    try:
        args.indir = os.path.abspath(args.indir)
    except:
        args.indir = os.path.abspath(os.getcwd())

    try:
        args.outdir = os.path.abspath(args.outdir)
    except:
        args.outdir = os.path.abspath(os.getcwd())

    try:
        args.configfile = os.path.abspath(args.configfile)
    except:
        args.configfile = None

    try:
        args.downsample = int(args.downsample)
    except:
        args.downsample = None

    try:
        args.bw_binsize = int(args.bw_binsize)
    except:
        args.bw_binsize = None

    return args


def main():
    args = parse_args()

    ## Require shared snakemake workflow directory
    this_script_dir = os.path.dirname(os.path.realpath(__file__))

    main_dir_path = os.path.join(os.path.dirname(os.path.dirname(this_script_dir)))
    if not os.path.isdir(main_dir_path):
        print("Error! Shared snakemake workflow directory is NOT available at:", main_dir_path)
        exit(1)

    ## Output directory + log directory
    cluster_logs_dir = os.path.join(args.outdir, "cluster_logs")
    subprocess.call("[ -d {cluster_logs_dir} ] || mkdir -p {cluster_logs_dir}".format(cluster_logs_dir=cluster_logs_dir), shell=True)

    ## required
    user_configs = "--config maindir={main_dir_path} indir={indir} genome={genome}".format(
                                main_dir_path = main_dir_path,
                                indir = args.indir,
                                genome = args.genome).split()

    ## optional
    if args.downsample:
        user_configs += ["downsample={}".format(args.downsample)]
    if args.trim:
        user_configs += ["trim=True"]
    if args.fastqc:
        user_configs += ["fastqc=True"]
    if args.bw_binsize:
        user_configs += ["bw_binsize={}".format(args.bw_binsize)]


    snakemake_module_load = "module load snakemake slurm &&".split()
    snakemake_cmd = """
                    snakemake --snakefile {snakefile} --jobs {max_jobs} {user_configs} --directory {outdir}
                    """.format( snakefile = os.path.join(this_script_dir, "Snakefile"),
                                max_jobs = args.max_jobs,
                                user_configs = " ".join(user_configs),
                                outdir = args.outdir,
                                cluster_logs_dir = os.path.abspath(cluster_logs_dir)
                              ).split()

    if args.configfile:
        snakemake_cmd += ["--configfile", args.configfile]

    if args.verbose:
        snakemake_cmd.append("--printshellcmds")

    if args.rerun_incomplete:
        snakemake_cmd.append("--rerun-incomplete")

    if args.forceall:
            snakemake_cmd.append("--forceall")

    if not args.local:
            snakemake_cmd.append("--cluster 'SlurmEasy --threads {{threads}} --log {cluster_logs_dir}' --jobname '{{rulename}}.{{jobid}}.snakejob'")

    snakemake_log = "2>&1 | tee -a {}/LOG".format(args.outdir).split()

    cmd = " ".join(snakemake_module_load + snakemake_cmd + snakemake_log)

    if args.verbose:
        print("\n", cmd, "\n")

    ## Write snakemake_cmd to log file
    with open(os.path.join(args.outdir,"LOG"),"w") as f:
        f.write(" ".join(sys.argv)+"\n\n")
        f.write(cmd+"\n\n")

    ## Run snakemake
    p = subprocess.Popen(cmd, shell=True)
    if args.verbose:
        print("PID:", p.pid, "\n")
    try:
        p.wait()
    except:
        print("\nWarning: Snakemake terminated!!!")
        if p.returncode != 0:
            if p.returncode:
                print("Returncode:", p.returncode)

            # kill snakemake and child processes
            subprocess.call(["pkill", "-SIGTERM", "-P", str(p.pid)])
            print("SIGTERM sent to PID:", p.pid)

            # # kill grid engine jobs
            # time.sleep(10)
            # job_ids = subprocess.check_output("""ls {cluster_logs_dir} | awk -F "." '{{print $NF}}' | sed 's/e\|o//' | sort -u""".format(cluster_logs_dir=cluster_logs_dir), shell=True).split()
            # for job_id in job_ids:
            #     subprocess.call( "qdel {} 2>&1 >/dev/null".format(str(job_id)), shell="bash" )


if __name__ == "__main__":
    #print "Args:", sys.argv
    main()
