# path names must end with "/" and not include the name of the executable
bedtools_path="/package/bedtools2-2.25.0/bin/"
bowtie2_path = "/package/bowtie2-2.2.8/bin/"
cutadapt_path = "/package/cutadapt-1.8.1/bin/"
deepTools_path = "/package/deeptools-develop-python2/bin/"
fastqc_path = "/package/FastQC-0.11.3/bin/"
histoneHMM_path = "/home/arichter/R/x86_64-unknown-linux-gnu-library/3.2/histoneHMM/bin/"
macs2_path = "/package/MACS2-2.1.0-20150731/bin/"
qualimap_path = "/package/qualimap-2.2/"
picard_path="/package/picard-tools-1.136/"
R_libs_path = "/home/arichter/R/x86_64-unknown-linux-gnu-library/3.2/"
R_path = "/package/R-3.2.3/bin/"
#rMATS_path = "/package/rMATS-3.2.1/RNASeq-MATS.py"
#rseqc_path = "/package/RSeQC-2.6.1/bin/"
samtools_path="/package/samtools-1.3.1/bin/"
tabix_path="/package/tabix-1.2.1/"
trim_galore_path = "/package/trim_galore_v0.4.0/bin/"
workflow_tools = os.path.join(maindir,"shared","tools")
