import os
import snakePipes.common_functions as cf


### snakemake_workflows initialization ########################################
maindir = os.path.dirname(os.path.dirname(workflow.basedir))

# load conda ENVs (path is relative to "shared/rules" directory)
globals().update(cf.set_env_yamls())
# load config file
globals().update(cf.load_configfile(workflow.overwrite_configfiles[0], config["verbose"]))
# load organism-specific data, i.e. genome indices, annotation, etc.
globals().update(cf.load_organism_data(genome, maindir, config["verbose"]))
# return the pipeline version in the log
cf.get_version()

# do workflow specific stuff now
include: os.path.join(workflow.basedir, "internals.snakefile")

### include modules of other snakefiles ########################################
################################################################################

# deeptools cmds
include: os.path.join(maindir, "shared", "tools" , "deeptools_cmds.snakefile")


include: os.path.join(maindir, "shared", "rules", "deepTools_RNA.snakefile")



if not fromBAM:
    ## FASTQ: either downsample FASTQ files or create symlinks to input files
    include: os.path.join(maindir, "shared", "rules", "FASTQ.snakefile")
    include: os.path.join(maindir, "shared", "rules", "umi_tools.snakefile")

    ## FastQC
    if fastqc:
        include: os.path.join(maindir, "shared", "rules", "FastQC.snakefile")

    ## Trim
    if trim:
        include: os.path.join(maindir, "shared", "rules", "tesmall.snakefile")


### conditional/optional rules #################################################
################################################################################
def run_FastQC(fastqc):
    readsUse = reads
    print(fastqc)
    print("Reads to use:" + str(reads))
    if not pairedEnd:
        readsUse = [reads[0]]
    if fastqc:
        return( expand("FastQC/{sample}{read}_fastqc.html", sample = samples, read = readsUse) )
    else:
        return([])

def run_Trimming(trim, fastqc):
    readsUse = reads
    if not pairedEnd:
        readsUse = [reads[0]]
    if trim and fastqc:
        return( expand(fastq_dir+"/{sample}.fastq.gz", sample = samples) +
                expand("FastQC_trimmed/{sample}_fastqc.html", sample = samples) )
    elif trim:
        return( expand(os.path.join(outdir,"FASTQ_fastp","{sample}.fastq.gz"), sample = samples )+
                expand(os.path.join(outdir,'TEsmallOut','TEsmall.done')) +
                expand(os.path.join(outdir,'TEsmallOut','count_summary_plot.pdf')) )
    else:
        return([])

### execute before  starts #####################################################
################################################################################
onstart:
    if "verbose" in config and config["verbose"] and not fromBAM:
        print()
        print("--- Workflow parameters --------------------------------------------------------")
        print("mode:", mode)
        print("samples:", samples)
        print("paired:", pairedEnd)
        print("read extension:", reads)
        print("fastq dir:", fastq_dir)
        print("filter GTF:", filterGTF)
        print("Sample sheet:", sampleSheet)
        print("TEsmall: ",tesmall_db)
        print("-" * 80, "\n")

        print("--- Environment ----------------------------------------------------------------")
        print("$TMPDIR: ", os.getenv('TMPDIR', ""))
        print("$HOSTNAME: ", os.getenv('HOSTNAME', ""))
        print("-" * 80, "\n")

    elif "verbose" in config and config["verbose"] and fromBAM:
        print("--- Workflow parameters --------------------------------------------------------")
        print("samples:" + str(samples))
        print("input dir:" + indir)
        print("paired:", pairedEnd)
        print("-" * 80)  # , "\n"

        print("--- Environment ----------------------------------------------------------------")
        print("$TMPDIR: " + os.getenv('TMPDIR', ""))
        print("$HOSTNAME: " + os.getenv('HOSTNAME', ""))
        print("-" * 80,)

    if toolsVersion:
        usedEnvs = [CONDA_SHARED_ENV, CONDA_RNASEQ_ENV]
        cf.writeTools(usedEnvs, outdir, "smRNAseq", maindir)
    if sampleSheet:
        cf.copySampleSheet(sampleSheet, outdir)

### main rule ##################################################################
################################################################################
if not fromBAM:
    rule all:
        input:
            expand("originalFASTQ/{sample}{read}.fastq.gz",sample=samples, read=reads),
            run_FastQC(fastqc),
            run_Trimming(trim, fastqc = False)

else:
    rule all:
        input:
            run_deepTools_qc(),
            run_deseq2()

### execute after  finished ####################################################
################################################################################
onsuccess:
    if "verbose" in config and config["verbose"]:
        print("\n--- smRNA-seq workflow finished successfully! ------------------------------------\n")

onerror:
    print("\n !!! ERROR in smRNA-seq workflow! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n")
