genome_size = "121400000"
genome_fasta = "/data/repository/organisms/dm6_ensembl/genome_fasta/genome.fa"
genome_2bit = "/data/repository/organisms/dm6_ensembl/genome_fasta/genome.2bit"
Bowtie2Index = "/data/repository/organisms/dm6_ensembl/BowtieIndex/genome"
genes_bed = "/data/repository/organisms/dm6_ensembl/Ensembl/release-79/genes.bed"
gtf = "/data/repository/organisms/dm6_ensembl/Ensembl/release-79/genes.gtf"
