name: conda-build

on: [pull_request, push]

jobs:
  condaBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: .github/conda_ci.yml
          condarc-file: .github/condarc.yml
          auto-activate-base: true
      - name: Install conda-build in base environment
          run: |
            conda install -n base -c conda-forge conda-build
      - name: buildSnakePipes
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          meta_yaml_dir: conda-recipe
          python-version: 3.11
          upload: false
