name: pytest

on: [pull_request, push]

defaults:
  run:
      shell: bash -l {0}

jobs:
  test_mRNA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: snakePipes/shared/rules/envs/rna_seq.yaml
        activate-environment: snakepipes_RNAseq_environment_3.0
        condarc-file: .github/condarc.yml
    - name: create_starix
      run: |
        gunzip -c tests/data/genomes/genome_chr17.fa.gz > genome_chr17.fa
        gunzip -c tests/data/genomes/genes_chr17.gtf.gz > genes_chr17.gtf
        STAR --runThreadN 4 --runMode genomeGenerate --genomeDir tests/data/mRNA_STAR --genomeFastaFiles genome_chr17.fa --sjdbGTFfile genes_chr17.gtf --sjdbOverhang 100 --genomeSAindexNbases 12
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: .github/snakePipesEnvCI.yml
        activate-environment: snakePipes_CI
        condarc-file: .github/condarc.yml
    - name: Install snakePipes
      run: |
        pip install .[actions]
    - name: pytest
      run: |
        snakePipes config --tempDir /tmp --condaEnvDir ./
        snakePipes createEnvs --only CONDA_SHARED_ENV CONDA_RNASEQ_ENV
        pytest --verbosity=2 -rP tests/test_mRNA.py
  CI_jobcounts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: .github/snakePipesEnvCI.yml
        activate-environment: snakePipes_CI
        condarc-file: .github/condarc.yml
    - name: Install snakePipes
      run: |
        pip install .[actions]
    - name: pytest
      run: |
        snakePipes config --tempDir /tmp --condaEnvDir ./
        pytest --verbosity=2 -rP tests/test_jobcounts.py
