#!/usr/bin/env python3

__description__ = """
MPI-IE workflow for DNA mapping

usage example:
    DNA-mapping -i input-dir -o output-dir mm10
"""


import argparse
import os
import sys
import textwrap
import snakePipes.common_functions as cf
import snakePipes.parserCommon as parserCommon


def parse_args(defaults={"verbose": False, "configfile": None,
                         "cluster_configfile": None, "max_jobs": 5,
                         "snakemake_options": "--use-conda", "tempdir": None,
                         "mode": "mapping", "downsample": False, "trim": False,
                         "trim_prg": "cutadapt", "trim_options": "",
                         "fastqc": False, "qualimap": False, "dedup": False,
                         "properpairs": False, "insert_size_max": 1000,
                         "gcbias": False, "bw_binsize": 25, "mapq": 0,
                         "plot_format": "png", "bowtie_opts": "",
                         "umidedup": False, "umidedup_opts": "",
                         "umidedup_sep": "_", "mate_orientation": "--fr"}):
    """
    Parse arguments from the command line.
    """
    mainArgs = parserCommon.mainArguments(defaults)
    snpArgs = parserCommon.snpArguments(defaults)

    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(__description__),
        parents=[mainArgs, snpArgs],
        add_help=False
    )


    # Workflow options
    optional = parser.add_argument_group('Options')
    optional.add_argument("-m", "--mode",
                          dest="mode",
                          help="workflow running modes (available: 'mapping,"
                          "allelic-mapping')(default: '%(default)s')",
                          default=defaults["mode"])

    parserCommon.commonOptions(optional, defaults)

    optional.add_argument("--bowtie_opts",
                          help="Options that will be passed to bowtie2."
                          "You can specify things such as `--local` or "
                          "`--very-sensitive` here. The mate orientation and "
                          "maximum insert size are specified elsewhere. Read "
                          "group information is set automatically. Note that "
                          "you may need to escape the first - "
                          "(e.g., '--very-fast'). (default: '%(default)s')",
                          default=defaults["bowtie_opts"])

    optional.add_argument("--umidedup",
                          dest="umidedup",
                          action="store_true",
                          help="To run `umi_tools dedup`."
                          "(default: '%(default)s')",
                          default=defaults["umidedup"])

    optional.add_argument("--umidedup_sep",
                          help="umi separation character "
                          "that will be passed to umi_tools."
                          "(default: '%(default)s')",
                          default=defaults["umidedup_sep"])

    optional.add_argument("--umidedup_opts",
                          help="Options that will be passed to umi_tools."
                          "(default: '%(default)s')",
                          default=defaults["umidedup_opts"])

    optional.add_argument("--mate_orientation",
                          help="The --fr, --ff, or --rf option for bowtie2 "
                          "(default: '%(default)s')",
                          default=defaults["mate_orientation"])

    optional.add_argument("--qualimap",
                          dest="qualimap",
                          action="store_true",
                          help="activate Qualimap (default: '%(default)s')",
                          default=defaults["qualimap"])

    optional.add_argument("--dedup",
                          dest="dedup",
                          action="store_true",
                          help="retain only de-duplicated reads/read pairs "
                          "(given single-/paired-end data), recommended for "
                          "ChIP-seq data (default: '%(default)s')",
                          default=defaults["dedup"])

    optional.add_argument("--properpairs",
                          dest="properpairs",
                          action="store_true",
                          help="retain only reads mapping in proper pairs "
                          "(default: '%(default)s')",
                          default=defaults["properpairs"])

    optional.add_argument("--mapq",
                          dest="mapq",
                          metavar="INT",
                          help="retain only reads with at least the given "
                          "mapping quality. We recommend using"
                          "mapq of 3 or more for ChIP-seq to remove all true "
                          "multimapping reads. (default: '%(default)s')",
                          type=int,
                          default=defaults["mapq"])

    optional.add_argument("--insert-size",
                          dest="insert_size_max",
                          metavar="INT",
                          help="Maximum insert size allowed during mapping "
                          "(default: '%(default)s')",
                          type=int,
                          default=defaults["insert_size_max"])

    optional.add_argument("--gcbias",
                          dest="gcbias",
                          action="store_true",
                          help="run computeGCBias quality control "
                          "(long runtime!). Note that gcbias analysis is "
                          "skipped if downsampling is specified "
                          "(default: '%(default)s')",
                          default=defaults["gcbias"])

    return parser


def main():
    baseDir, workflowDir, defaults = cf.setDefaults(os.path.basename(__file__))

    # get command line arguments
    parser = parse_args(defaults)
    args = parser.parse_args()
    args, defaults = cf.handleUserArgs(args, defaults, parse_args)

    # we also add these paths to config, although we don't use them in the Snakefile
    args.baseDir = baseDir

    # Common arguments
    cf.checkCommonArguments(args, baseDir, outDir=True)

    ## Begin workflow-specific code
    # check for Allele-specific mapping mode
    args.allele_mode = cf.checkAlleleParams(args)
    # convert file path to abspath
    if args.allele_mode == "create_and_map":
        args.VCFfile = os.path.abspath(args.VCFfile)
    elif args.allele_mode == "map_only":
        args.SNPfile = os.path.abspath(args.SNPfile)
        args.Nmasked_index = os.path.abspath(args.Nmasked_index)

    # clean up filtered_bam if needed appropriate
    os.makedirs(args.outdir, exist_ok=True)
    filt = ""
    if args.dedup:
        filt += "-F 1024 "
        assert args.umidedup is False, "Either umitools dedup or samtools "
        "should be called!"
    if args.properpairs:
        filt += "-f 2 "
    if args.mapq is not None and args.mapq > 0:
        filt += "-q {} ".format(args.mapq)
    filter_rules = os.path.join(args.outdir, "filter_rules")
    if os.path.exists(filter_rules):
        f = open(filter_rules)
        cont = f.read()
        f.close()
        if cont != filt:
            f = open(filter_rules, "w")
            f.write(filt)
            f.close()
    else:
        f = open(filter_rules, "w")
        f.write(filt)
        f.close()
    ## End workflow-specific clode

    # Handle YAML and log files
    snakemake_cmd = cf.commonYAMLandLogs(baseDir, workflowDir, defaults,
                                         args, __file__)
    snakemake_exports, logfile_name, temp_path = cf.logAndExport(args, os.path.basename(__file__))

    cmd = " ".join(snakemake_exports + snakemake_cmd)

    # Run everything
    cf.runAndCleanup(args, cmd, logfile_name, temp_path)


if __name__ == "__main__":
    main()
